# Generated by Django 4.1.3 on 2022-11-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_applied', models.BooleanField(default=False)),
                ('coupen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.coupon')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
    ]
