# Generated by Django 4.1.3 on 2022-11-30 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_mainbanner_category_alter_mainbanner_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbanner',
            name='category',
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.subcategory'),
        ),
    ]
